Feature/posts
lucasborges24/projeto17-linkr-back pull request #5
Opened 2022-08-11 12:15 UTC by nando-castro

Implementado retorno de posts dos usuários

2022-08-11 17:24 UTC, Caio-Pedras commented on src/controllers/postController.js
> +    const createdAt = dayjs().format("YYYY-MM-DD HH:mm:ss");
O createdAt já está como default NOW() no próprio banco de dados. 
Imagino que seja interessante padrozinar deixando ele como NOW() mesmo, apesar das duas formas funcionar

2022-08-11 17:36 UTC, Caio-Pedras commented on src/controllers/postController.js
> +}
Falta identificar as hashtags presentes em description para inseri-las na database.
É uma funcionalidade que estará nessa branch ou em outra?

2022-08-11 17:37 UTC, Caio-Pedras commented on src/repositories/postRepository.js
> +}
Pensando nas funcionalidades de deletar, editar e like, acredito ser importante enviar o id do post para conseguirmos acessar o post que terá interação no futuro

2022-08-11 22:02 UTC, nando-castro commented on src/controllers/postController.js
> +    const createdAt = dayjs().format("YYYY-MM-DD HH:mm:ss");
Vou remover a variável createAt e deixar o padrão do banco.

2022-08-11 22:02 UTC, nando-castro commented on src/repositories/postRepository.js
> +}
Já adicionei o id.

2022-08-11 22:02 UTC, nando-castro commented on src/controllers/postController.js
> +}
Vou criar uma branch somente para essa solução.

2022-08-12 03:52 UTC, andreseichi approved these changes

2022-08-12 22:58 UTC, lucasborges24 requested changes

2022-08-12 22:58 UTC, lucasborges24 commented on src/controllers/postController.js
> +    console.log(error);
Acabou passando esse console.log

2022-08-12 22:58 UTC, lucasborges24 commented on src/controllers/postController.js
> +export async function createdPost(req, res) {
A função cria posts, então um nome mais semântico seria `createPost`

2022-08-12 22:58 UTC, lucasborges24 commented on src/repositories/postRepository.js
> +async function createdHashtags(hashtagName) {
Aqui também seria uma criação de Hashtags, então acho que ficaria melhor um `createHashtag`

2022-08-12 22:58 UTC, lucasborges24 commented on src/middlewares/metadataMiddleware.js
> +    console.log(err);
console log

2022-08-12 23:19 UTC, nando-castro reviewed
Alterações sugeridas adicionadas.

2022-08-12 23:19 UTC, nando-castro commented on src/controllers/postController.js
> +    console.log(error);
Vou alterar

2022-08-12 23:19 UTC, nando-castro commented on src/controllers/postController.js
> +export async function createdPost(req, res) {
Vou alterar

2022-08-12 23:19 UTC, nando-castro commented on src/repositories/postRepository.js
> +async function createdHashtags(hashtagName) {
Adicionei as alterações

2022-08-12 23:33 UTC, andreseichi approved these changes

2022-08-12 23:33 UTC, merged